# Table of Contents
- [1. Introduction](#1)
    - [1.1 Definitions and Terminology](#1_1)
    - [1.2 Machine Learning Concepts](#1_2)
    - [1.3 Technology](#1_3)
    - [1.4 Exercise](#1_4)
    - [1.5 Learning Material](#1_5)


## 1. Introduction<a name="1"></a>

### 1.1 Definitions and Terminology<a name="1_1"></a>

#### What is machine learning?

Machine learning (ML) is a **field of artificial intelligence** that uses statistical techniques to give computer systems the ability to **learn (...) from data**, without being explicitly programmed.
The name machine learning was coined in 1959 by Arthur Samuel.

[Wikipedia ML](https://en.wikipedia.org/wiki/Machine_learning)
<img alt="ML AI venn diagram" src="../img/1/ML_AI_venn.png" width=200>

#### What is statistical learning?
- Machine Learning is a subfield of computer science / artificial intelligence focussing on prediction accuracy and big data 
- **Statistical Learning** is a subfield of statistics focussing on model interpreatbility
- Both Machine Learning and Statistical learning focus on supervised and unsupervised learning. They have a lot of overlap.



#### What is AI?
 In computer science AI research is defined as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.
[Wikipedia AI](https://en.wikipedia.org/wiki/Artificial_intelligence)

#### Neural Networks
Artificial neural networks (ANN) or connectionist systems are computing systems vaguely inspired by the biological neural networks that constitute animal brains.
[Wikipedia NN](https://en.wikipedia.org/wiki/Artificial_neural_network) 

A deep neural network (DNN) is an artificial neural network (ANN) with multiple layers between the input and output layers.
[Wikipedia Deep Neural Networks](https://en.wikipedia.org/wiki/Deep_learning#Neural_networks)

### 1.2 Machine Learning Concepts<a name="1_2"></a>

#### Difference between traditional programming and Machine Learning


<img src="../img/1/ML_vs_trad.png" width=400 alt="ML vs traditional programming">


#### General Concept
The learning problem is characterized by **observations** comprised of: **input data (X)** and **output data (y)** and some unknown but **coherent relationship** between the two.

![ML mapping input to output](../img/1/ml_in_out.png)

The goal of the learning system is to **learn a generalized mapping** between input and output data such that skillful predictions can be made for new instances drawn from the domain where the output variable is unknown.

In statistical learning the problem is framed as the learning of a **target function ($f$)** given **input data (X)** and associated **output data (y)**.

$$y = f(X)$$

We have a sample of X and y and do our best to come up with a **function  $\hat{f}$ that approximates $f$**, so that we can make **predictions ($\hat{y}$)** given **new examples ($X$)** in the future.

$$\hat{y} = \hat{f}(X)$$

$\hat{y}, \hat{f}$ are pronounced **y-hat** and **f-hat**

[machinelearningmastery](https://machinelearningmastery.com/applied-machine-learning-as-a-search-problem/)

#### A Simple Example
<table>
    <tr>
        <td  style="text-align:left" width=300>
            When looking at data one tries to identify patterns in the data as shown here. 
            We wonder what is the cause of that pattern. 
            We can build a <em>model</em> to try to explain the pattern we observe.
            <ul>
                <li> Y is the dependant variable, outcome, response, target</li>                
                <li> X is the independent variable, features</li>
            </ul>
        </td>
        <td>
            <img alt="simple example" src="../img/1/simple_example.png" width=400>
        </td>
    </tr>
</table>



We believe there is a true mechanism (target function $\color{red}{ f(x)}$) that describes the relationship between our variables. The aim of machine learning is to find a model (model $\color{blue}{ \hat{f}(x)}$) that estimates this function from the data. 

![estimating the target function](../img/1/target_function.jpg)

#### Supervised and Unsupervised Learning

On the highest level machine learning can be subdived into *supervised* and *unsupervised learning*.

The criteria is the presence or absence of **labels**. 

Next you see some code to generate a data frame with random numbers.

Rows are **observations** or **samples**. Columns 0-4 are **features**. Y is the **class label**.

In [1]:
from sklearn.datasets import make_classification

# Create a simulated feature matrix and output vector
X, y = make_classification(n_samples = 100, n_features = 5, n_informative = 3, n_redundant = 2,
                                       n_classes = 3, weights = [.2, .3, .5])

In [2]:
# View the first 10 observations
print(type(X), X.shape)
print(X[0:10,:], "\n")

# View the first 10 labels
print(type(y), y.shape)
print(y[0:10])

<class 'numpy.ndarray'> (100, 5)
[[-0.61217539 -0.01237205 -0.55760062 -1.67522683 -1.54430197]
 [-0.87266505 -0.30191277 -0.53197636 -0.88110136 -0.75391875]
 [-0.12190896  0.03802741  0.8672277   0.5574543  -0.25156704]
 [-0.20192191 -0.52742869 -0.16299584  1.71764457  2.03594949]
 [-1.54253199 -0.86255376  0.90378085  1.86241026  0.73948292]
 [-1.31997846 -0.45774819  0.77796225  0.39473855 -0.72666822]
 [-2.59584468 -1.6331548  -2.00201922  0.07896652  1.21659847]
 [ 1.66522562  0.9429556   2.52805008  1.75295036  0.04872616]
 [-1.3740722  -0.61616176  1.70074938  1.98047762  0.15126028]
 [-1.83782376 -0.94419681 -2.85309034 -2.41761557 -0.53835   ]] 

<class 'numpy.ndarray'> (100,)
[1 1 0 2 2 0 1 2 2 1]


#### Supervised Learning
you start with
- y = outcome measurement (label, dependent variable, response, target)
	- regression problem y is continuous (5, 3.456, 1023) 
	- classification problem y is discrete (yes/no, A,B,C)
- X = vector of predictor measurement (independent variable, features)
- training data: observations of measurements: $(x_1,y_1), (x_2,y_2), (x_3,y_3) ... (x_n,y_n)$


e.g. Classification, Regression

You will learn more about [supervised learning](2_supervised_learning.ipynb) in the next class.

#### Unsupervised Learning
you start with
- no outcome variable
- X = vector of measurements(independent variable, features)
- objective is more fuzzy: groups samples, find features
- more difficult to evaluate, but easier to get training data
- observations of measurements: $x_1, x_2, x_3 ... x_n$


Objectives are more fuzzy for unsupervised learning

Using the training data we want:
- Find samples that behave similarly
- Find features that behave similarly
- Difficult to assess quality

e.g. Clustering
<img src="../img/1/cats_and_dogs.png" alt="cats and dogs" width=500>

You will learn more about [unsupervised learning](3_unsupervised_learning.ipynb) later today.

Unsupervised vs Supervised Learning

<img src="../img/1/cluster_vs_classify.png" alt="clustering vs classification" width=500>

source: https://deepcast.ai/media/article3/

#### Concept Map
<table>
    <tr>
        <td>
            <img src="../img/1/machine_learning_cmap.jpg" alt="ML concept map" width=500>
        </td>
        <td>
            <img src="../img/1/ML_concept_map.png" alt="ML concept map" width=250>
        </td>
    </tr>
</table>


#### Regression vs Classification
Supervised learning problems can be further divided into regression and classification problems.
This depends on the **data type of the target variable y**.

1. Regression covers situations where y is **numerical**. e.g.
    - Predicting the **value** of the DAX next week.
    - Predicting the **price** of a given house based on various inputs.


2. Classification covers situations where y is **categorical-nominal** e.g.
    - Will the DAX be **up or down** next week?
    - Is this email a **SPAM or not**?        


- Either regression or classification could be used if y is **categorical-ordinal** e.g.
    - Predict the grade in an exam (A, B, C, D, F) based on hours studied for the exam.
    - Predict the bank credit rating based on bank features.

  Regression is usually more appropriate here.

<img src="../img/1/categorical_numerical_vars.jpg" width=350>


#### Why do we estimate $f(x)$? 

There are 2 reasons:
1. Prediction
2. Inference

##### Prediction
If we can produce a good estimate for f, we can make accurate predictions for the response Y, based on a new value of X.

E. g. predicting how much money someone will earn based on education level and age.

##### Inference
Alternatively, we may also be interested in **understanding** the type of relationship between Y and the X's. For example, 
- Which particular feature actually affect the response? 
- Is the relationship positive or negative? 
- Is the relationship a simple linear one or is it more complicated etc.?


##### There is a Trade-off: Prediction vs Inference
Simple models are often advantageous for both prediction as well as Inference.
- Simple models are easier to interpret. Easier to understand.
- Also, a simple model is often easier to train. It is harder to fit a flexible model. Only really complex tasks require more flexible models such as neural networks.

Take home message: Always start with a simple model.

### 1.3 Technology<a name="1_3"></a>
Have a look at the technology used in this course [technologies.md](../md/technologies.md).


**Scikit-learn** is a collection of ML methods that can be used throughout any data science project.

Here is an example on a simple classification model. The procedure is always the same:

1. split the data into train and test
2. create a model
3. fit (learning from train data)
4. predict (using the model to make predicionts on test data)
5. evaluate predictions


#### 1. split the data into train and test
##### Assessing Model Quality
- How do we know if the model we build is close enough to the target function?
- How good are our predictions?

We need to test our model. One way to do this is to **split our data** set into:
    - train 
    - test


In [3]:
from sklearn.model_selection import train_test_split
THE_ANSWER=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=THE_ANSWER)
print("Train data X and y: ", X_train.shape, y_train.shape)
print("Test data X and y: ", X_test.shape, y_test.shape)

Train data X and y:  (70, 5) (70,)
Test data X and y:  (30, 5) (30,)


#### 2. create a model

In [7]:
from sklearn import svm
# our model is a classifier clf
clf = svm.SVC()
print(clf)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


#### 3. fit the model

In [8]:
print(X_train.shape, y_train.shape)
print(X_train.dtype, y_train.dtype)
print(type(X_train), type(y_train))
clf.fit(X_train, y_train)

(70, 5) (70,)
float64 int32
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

#### 4. Predict
Now you can use the model to make predictions and compare with the truth.

In [9]:
y_pred = clf.predict(X_test)
print("test:", y_test)
print("pred:", y_pred)


test: [2 1 2 2 1 0 2 1 1 1 0 2 0 1 0 2 2 0 2 2 0 1 2 0 2 0 2 2 1 1]
pred: [2 1 2 2 1 0 2 1 2 1 0 2 2 1 0 2 2 0 2 2 2 1 2 0 2 1 2 2 1 2]


##### 5. Evaluate

In [10]:
print("sum of correct predictions", sum(y_test == y_pred))
print("length of predictions", len(y_pred))

print("accuracy: ", sum(y_test == y_pred) / len(y_pred))

sum of correct predictions 25
length of predictions 30
accuracy:  0.8333333333333334


## 1.4 Exercise<a name="1_4"></a>
- Change the code in this function: **make_classification**.  [API doc on make_classification](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html)
    	What happens to the accuracy, if you change the values for
        n_samples, n_features, n_informative, n_redundant, n_classes, weights?
- Change the random_state in the function **train_test_split**. [API doc on train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)
        What does this do?

## 1.5 Learning Material<a name="1_5"></a>

- [machinelearningmastery](https://machinelearningmastery.com/applied-machine-learning-as-a-search-problem/)
- [ISLR](http://www-bcf.usc.edu/~gareth/ISL/)
- [train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)
- [make_classification](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_classification.html)